@extends('layouts.app')

@section('content')
<div class="container main-content">
    <h2>Scoring Tables</h2>
    <div class="row">
    	<div class="table-responsive col-md-6">
            <h3>Men's Scoring Table</h3>
    		<table class="table table-hover">
    		    <tbody>
    		        <tr>
    		            <td>
    		                <p><span><strong>Position</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span><strong>Points</strong></span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>1</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>500</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>2</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>450</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>3</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>420</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>4</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>400</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>5</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>390</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>6</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>380</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>7</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>370</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>8</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>360</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>9</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>350</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>10</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>340</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>11</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>330</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>12</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>320</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>13</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>310</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>14</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>300</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>15</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>290</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>16</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>280</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>17</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>270</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>18</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>260</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>19</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>250</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>20</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>240</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>21</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>230</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>22</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>220</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>23</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>210</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>24</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>200</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>25</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>190</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>26</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>180</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>27</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>170</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>28</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>160</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>29</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>150</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>30</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>145</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>31</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>140</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>32</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>135</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>33</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>130</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>34</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>125</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>35</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>120</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>36</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>115</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>37</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>110</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>38</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>105</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>39</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>100</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>40</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>95</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>41</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>90</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>42</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>85</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>43</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>80</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>44</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>75</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>45</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>70</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>46</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>65</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>47</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>60</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>48</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>55</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>49</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>50</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>50</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>49</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>51</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>48</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>52</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>47</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>53</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>46</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>54</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>45</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>55</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>44</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>56</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>43</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>57</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>42</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>58</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>41</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>59</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>40</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>60</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>39</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>61</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>38</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>62</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>37</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>63</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>36</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>64</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>35</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>65</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>34</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>66</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>33</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>67</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>32</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>68</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>31</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>69</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>30</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>70</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>29</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>71</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>28</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>72</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>27</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>73</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>26</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>74</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>25</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>75</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>24</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>76</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>23</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>77</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>22</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>78</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>21</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>79</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>20</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>80</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>19</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>81</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>18</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>82</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>17</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>83</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>16</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>84</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>15</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>85</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>14</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>86</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>13</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>87</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>12</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>88</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>11</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>89</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>10</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>90</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>9</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>91</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>8</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>92</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>7</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>93</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>6</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>94</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>5</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>95</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>4</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>96</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>3</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>97</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>2</span></p>
    		            </td>
    		        </tr>
    		        <tr>
    		            <td>
    		                <p><span><strong>98</strong></span></p>
    		            </td>
    		            <td>
    		                <p><span>1</span></p>
    		            </td>
    		        </tr>
    		    </tbody>
    		</table>
    	</div><!-- /.table-responsive -->
        <div class="table-responsive col-md-6">
            <h3>Women's Scoring Table</h3>
            <table class="table table-hover">
                <tbody>
                    <tr>
                        <td>
                            <p><span><strong>Position</strong></span></p>
                        </td>
                        <td>
                            <p><span><strong>Points</strong></span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>1</strong></span></p>
                        </td>
                        <td>
                            <p><span>400</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>2</strong></span></p>
                        </td>
                        <td>
                            <p><span>350</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>3</strong></span></p>
                        </td>
                        <td>
                            <p><span>320</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>4</strong></span></p>
                        </td>
                        <td>
                            <p><span>300</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>5</strong></span></p>
                        </td>
                        <td>
                            <p><span>290</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>6</strong></span></p>
                        </td>
                        <td>
                            <p><span>280</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>7</strong></span></p>
                        </td>
                        <td>
                            <p><span>270</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>8</strong></span></p>
                        </td>
                        <td>
                            <p><span>260</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>9</strong></span></p>
                        </td>
                        <td>
                            <p><span>250</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>10</strong></span></p>
                        </td>
                        <td>
                            <p><span>240</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>11</strong></span></p>
                        </td>
                        <td>
                            <p><span>230</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>12</strong></span></p>
                        </td>
                        <td>
                            <p><span>220</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>13</strong></span></p>
                        </td>
                        <td>
                            <p><span>210</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>14</strong></span></p>
                        </td>
                        <td>
                            <p><span>200</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>15</strong></span></p>
                        </td>
                        <td>
                            <p><span>190</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>16</strong></span></p>
                        </td>
                        <td>
                            <p><span>180</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>17</strong></span></p>
                        </td>
                        <td>
                            <p><span>170</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>18</strong></span></p>
                        </td>
                        <td>
                            <p><span>160</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>19</strong></span></p>
                        </td>
                        <td>
                            <p><span>150</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>20</strong></span></p>
                        </td>
                        <td>
                            <p><span>145</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>21</strong></span></p>
                        </td>
                        <td>
                            <p><span>140</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>22</strong></span></p>
                        </td>
                        <td>
                            <p><span>135</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>23</strong></span></p>
                        </td>
                        <td>
                            <p><span>130</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>24</strong></span></p>
                        </td>
                        <td>
                            <p><span>125</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>25</strong></span></p>
                        </td>
                        <td>
                            <p><span>120</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>26</strong></span></p>
                        </td>
                        <td>
                            <p><span>115</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>27</strong></span></p>
                        </td>
                        <td>
                            <p><span>110</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>28</strong></span></p>
                        </td>
                        <td>
                            <p><span>105</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>29</strong></span></p>
                        </td>
                        <td>
                            <p><span>100</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>30</strong></span></p>
                        </td>
                        <td>
                            <p><span>95</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>31</strong></span></p>
                        </td>
                        <td>
                            <p><span>90</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>32</strong></span></p>
                        </td>
                        <td>
                            <p><span>85</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>33</strong></span></p>
                        </td>
                        <td>
                            <p><span>80</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>34</strong></span></p>
                        </td>
                        <td>
                            <p><span>75</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>35</strong></span></p>
                        </td>
                        <td>
                            <p><span>70</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>36</strong></span></p>
                        </td>
                        <td>
                            <p><span>65</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>37</strong></span></p>
                        </td>
                        <td>
                            <p><span>60</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>38</strong></span></p>
                        </td>
                        <td>
                            <p><span>55</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>39</strong></span></p>
                        </td>
                        <td>
                            <p><span>50</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>40</strong></span></p>
                        </td>
                        <td>
                            <p><span>45</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>41</strong></span></p>
                        </td>
                        <td>
                            <p><span>40</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>42</strong></span></p>
                        </td>
                        <td>
                            <p><span>35</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>43</strong></span></p>
                        </td>
                        <td>
                            <p><span>30</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>44</strong></span></p>
                        </td>
                        <td>
                            <p><span>25</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>45</strong></span></p>
                        </td>
                        <td>
                            <p><span>20</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>46</strong></span></p>
                        </td>
                        <td>
                            <p><span>15</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>47</strong></span></p>
                        </td>
                        <td>
                            <p><span>10</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>48</strong></span></p>
                        </td>
                        <td>
                            <p><span>5</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>49</strong></span></p>
                        </td>
                        <td>
                            <p><span>3</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><span><strong>50</strong></span></p>
                        </td>
                        <td>
                            <p><span>1</span></p>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div><!-- /.table-responsive -->
    </div><!-- /.row -->
</div>
@endsection
